### ISSUE TITLE
Missing classes : OPUmlClassPlugin, OPUmlInheritanceController, OPUmlMethodController, etc

### ISSUE THREAD

**Issue by hernanmd** [OpenPonk/class-editor#24]
When I try to load the packages LiveClassEditor or UMLClassEditor there are references to classes which are not present in the repositories:

LiveClassEditor depends on OPUmlClassPlugin, OPUmlInheritanceController, OPUmlMethodController, OPUmlClassDiagramController
UMLClassEditor-Cormas depends on OPUmlClassPlugin

Are these classes available anywhere?

**Comment by JanBliznicenko** [comment]
Hello, @hernanmd. Assigning this issue to @peteruhnak - author of these packages - as I, unfortunately, do not use or even know the purpose of LiveClassEditor.

**Comment by hernanmd** [comment]
Ok, I found the clases in a DynaCASE repository and I'm re-integrating them with OP prefixes.

**Comment by peteruhnak** [comment]
> When I try to load the packages LiveClassEditor

Skimming through the code it seems that LiveClassEditor was just an experiment for directly editing live Smalltalk code/classes.

> OPUmlClassPlugin, OPUmlInheritanceController, OPUmlMethodController, OPUmlClassDiagramController

All of these classes were the diagram editor for FAMIX/Moose-based model (the one in Cormas+DynaCASE) and were since removed/replaced by their current equivalent (but using UML as model):

* OPUmlClassPlugin -> OPUmlClassEditorPlugin
* OPUmlInheritanceController -> OPUmlGeneralizationController
* OPUmlMethodController -> OPUmlOperationController
* OPUmlClassDiagramController -> OPUmlPackageDiagramController

**Comment by hernanmd** [comment]
Thanks for the answer @peteruhnak 
I will close the issue because I didn't knew it was an experiment.
